import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const tools = process.argv[2] === "tools";
const analyze = process.argv.includes("--analyze");

const rebuildPlugin = {
	name: "rebuild-handler",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;

			await fs.promises.rename("dist/main.css", "dist/styles.css");
			await fs.promises.copyFile(
				path.join(path.resolve(), "manifest.json"),
				path.join(path.resolve(), "dist", "manifest.json")
			);
			if (analyze) {
				await fs.promises.writeFile(
					"dist/metafile.json",
					JSON.stringify(result.metafile, null, 2)
				);
				await fs.promises.writeFile(
					"dist/bundle-analysis.txt",
					await esbuild.analyzeMetafile(result.metafile, { verbose: true })
				);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	// Preserve names used in diagnostics and by dependencies.
	keepNames: true,
	metafile: analyze,
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
		"process.env.ENABLE_REACT_DEVTOOLS": tools
			? JSON.stringify("true")
			: JSON.stringify("false"),
	},
	treeShaking: true,
	outdir: "dist",
	plugins: [rebuildPlugin],
});

if (prod) {
	try {
		await context.rebuild();
	} finally {
		await context.dispose();
	}
} else {
	await context.watch();
}
